src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     */
    private $category_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategoryId(): ?Category
    {
        return $this->category_id;
    }

    public function setCategoryId(?Category $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getName();
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('price')
            ->add('image')
            ->add('description')
            ->add('category_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\AfrekenenFormType;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Swift_Message;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

/**
 * @Route("/product")
 */
class ProductController extends AbstractController
{
    private $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    /**
     * @Route("/", name="product_index", methods={"GET"})
     */
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('product/index.html.twig', [
            'products' => $productRepository->findAll(),
            'cart' => $this->session->get('cart')
        ]);
    }

    /**
     * @Route("/checkout/", name="product_checkout", methods={"GET","POST"})
     */
    public function checkout(\Swift_Mailer $mailer, Request $request){
        $cart = $this->session->get('cart', []);
        $message = (new Swift_Message())
            ->setSubject('Here should be a subject')
            ->setTo('recipient@example.com')
            ->setFrom(['support@mailtrap.io'])
            ->setBody(
            $this->renderView(
                'product/mail.html.twig',[
                    'cart' => $cart,
                    'name' => $request->request->get('afrekenen_form')['name'],
                    'email' => $request->request->get('afrekenen_form')['email'],
                    ]),
            'text/html'
        );

        $mailer->send($message);

        return $this->render('product/checkout.html.twig', [
            'cart' => $cart,
            'name' => $request->request->get('afrekenen_form')['name'],
            'email' => $request->request->get('afrekenen_form')['email'],
        ]);
    }

    /**
     * @Route("/new", name="product_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('product_index');
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="product_show", methods={"GET"})
     */
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="product_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Product $product): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('product_index');
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="product_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('product_index');
    }
    /**
     * @Route("/{id}/cart", name="product_cart", methods={"GET","POST"})
     */
    public function AddToCart(Product $product, Request $request)
    {
        $cart = $this->session->get('cart', []);
        $form = $this->createForm(AfrekenenFormType::class);

        if(isset($cart[$product->getId()])){
            $cart[$product->getId()]['aantal']++;
        }
        else{
            $cart[$product->getId()] = array(
                'aantal' => 1,
                'name' =>$product->getName(),
                'price' => $product->getPrice(),
                'id' =>$product->getId(),
            );
        }
        if ($request->isMethod('POST')) {
            $form->submit($request->request->get($form->getName()));

            if ($form->isSubmitted() && $form->isValid()) {
                // perform some action...

                return $this->redirectToRoute('product_checkout', [
                    'form' => $form->getData()
                ]);
            }
        }
        $this->session->set('cart', $cart);
        return $this->render('product/cart.html.twig',[
            'product' => $cart[$product->getId()]['name'],
            'aantal' => $cart[$product->getId()]['aantal'],
            'cart' => $cart,
            'form' => $form->createView()
        ]);
    }
}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/product/cart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cart product{% endblock %}

{% block body %}
    {% set cart_total = 0 %}
        {% for cart in cart %}

           Product name : {{ cart.name }} <br>
           Product price:  {{ cart.price }}  <br>
           Amount of times:   {{ cart.aantal }} <br>
            {% set cart_total = cart_total + (cart.price * cart.aantal)  %}
            <br><br>

        {% endfor %}
       Totaal prijs: {{ cart_total }}

    {{ form(form, {'action': path('product_checkout'), 'method': 'POST'}) }}
    {{ form_start(form) }}
    {{ form_errors(form) }}

    {{ form_row(form.name) }}
    {{ form_row(form.email) }}

    {{ form_row(form.submit, { 'Label': 'Afrekenen' }) }}
    {{ form_end(form) }}

{% endblock %}

templates/product/checkout.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cart product{% endblock %}

{% block body %}
    {% set cart_total = 0 %}
    Naam:{{ name }}<br>
    Email: {{ email }}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Amount</th>
        </tr>
        </thead>
        <tbody>
        <tr>{% for cart in cart %}
            {% set cart_total = cart_total + (cart.price * cart.aantal)  %}
            <th scope="row">{{ cart.name }}</th>
            <td>{{ cart.price }}</td>
            <td>{{ cart.aantal }}</td>

        </tr>{% endfor %}

            <br><br>

        </tbody>
    </table>

    Totaal prijs: {{ cart_total }}
{% endblock %}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('product_index') }}">back to list</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}
    <h1>Product index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price</th>
                <th>Image</th>
                <th>Description</th>
                <th>Category</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.image }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.categoryId }}</td>
                <td>
                    <a href="{{ path('product_show', {'id': product.id}) }}">show</a>
                    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>
                    <a href="{{ path('product_cart', {'id': product.id}) }}">add to cart</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('product_new') }}">Create new</a>

{% endblock %}

templates/product/mail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cart product{% endblock %}

{% block body %}
    {% set cart_total = 0 %}
    Naam: Batuhan Güngör<br>
    Email: batuhan@gungor.nl
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Amount</th>
        </tr>
        </thead>
        <tbody>
        <tr>{% for cart in cart %}
            {% set cart_total = cart_total + (cart.price * cart.aantal)  %}
            <th scope="row">{{ cart.name }}</th>
            <td>{{ cart.price }}</td>
            <td>{{ cart.aantal }}</td>

        </tr>{% endfor %}

        <br><br>

        </tbody>
    </table>
    Totaal prijs: {{ cart_total }}
{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('product_index') }}">back to list</a>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <h1>Product</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ product.name }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ product.price }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ product.image }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ product.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('product_index') }}">back to list</a>

    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}